### ISSUE TITLE
Run it on boot issues

### ISSUE THREAD

**Issue by ghost** [RNA3210d/RPi-TELEBOT#2]
I use a raspberry pi zero w and this works great when I run it manually.
But I'd love have it when the device boots up. 
I been looking around trying to use rc.local and now crontab. Neither seems to start the bot as it doesn't respond on telegram.
With crontab I now made it output the error and it looks like:

`GNU nano 3.2 error.txt                                           
Traceback (most recent call last):
  File "/home/pi/RPi-TELEBOT/gpiotel20.py", line 77, in <module>
    print (bot.getMe())
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 503, in getMe
    return self._api_request('getMe')
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 154, in request
    r = fn(*args, **kwargs) # `fn` must be thread-safe
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python2.7/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max ret$`

Is there any advice how I would make this project start up on boot?
Thanks in advance

**Comment by wjmb** [comment]
What about running it as a service?

For example, as described here: https://gist.github.com/emxsys/a507f3cad928e66f6410e7ac28e2990f
